Feature/createuser
ayush2k/securbank pull request #36
Opened 2016-10-02 08:19 UTC by ayush2k

Resolves #35, Resolves #36.
Description:
- External User sign up
- Internal User sign up
- Email Service
- Validators

2016-10-04 06:49 UTC, ayush2k commented
@Mitikaa please review

2016-10-08 02:24 UTC, wchrismontgomery commented on src/main/resources/application.properties
> +/pring.datasource.driver-class-name = com.mysql.jdbc.Driver
This typo should be fixed.

2016-10-08 02:26 UTC, wchrismonty requested changes

2016-10-08 02:26 UTC, wchrismontgomery commented on src/main/resources/application.properties
> +/pring.datasource.driver-class-name = com.mysql.jdbc.Driver
This typo should be fixed.

2016-10-08 02:27 UTC, ayush2k commented on src/main/resources/application.properties
> +/pring.datasource.driver-class-name = com.mysql.jdbc.Driver
@wchrismontgomery fixed. thanks!

2016-10-08 02:39 UTC, wchrismonty approved these changes

2016-10-10 23:46 UTC, merged