Request
ayush2k/securbank pull request #63
Opened 2016-10-13 07:43 UTC by ayush2k

Resolves #37, Resolves #61, Resolves #62 
Description:
- External User can initiate modification request for profile
- Internal Users can view and approve or reject requests
- Admin can approve or reject internal user requests

2016-10-16 23:43 UTC, Nikh13 requested changes
Few minor changes. Let me know when theyre done. Ill merge.

2016-10-16 23:43 UTC, Nikh13 commented on src/main/java/securbank/controller/AdminController.java
> +		if (status == null || !(request.getStatus().equals("approved") || !request.getStatus().equals("rejected"))) {
When you reject a request it gives an error. The logic isn't right here. The ! outside is fine but there shouldn't be another one inside for 'rejected'.

2016-10-16 23:43 UTC, Nikh13 commented on src/main/java/securbank/controller/EmployeeController.java
> +		if (status == null || !(request.getStatus().equals("approved") || !request.getStatus().equals("rejected"))) {
Same bug as admincontroller.

2016-10-16 23:43 UTC, Nikh13 commented on src/main/java/securbank/controller/ManagerController.java
> +		if (status == null || !(request.getStatus().equals("approved") || !request.getStatus().equals("rejected"))) {
Same bug as admincontroller.

2016-10-16 23:43 UTC, Nikh13 commented on src/main/resources/templates/employee/detail.html
> +			<p><a th:href="@{employee/edit}">Edit</a></p>
This should be /employee/edit

2016-10-16 23:43 UTC, Nikh13 commented on src/main/resources/templates/manager/detail.html
> +        <title>Details</title>
Similar to the employee details page, the link to the edit page should be /employee/edit and needs to be changed for external user as well.

2016-10-18 23:06 UTC, Nikh13 requested changes

2016-10-18 23:06 UTC, Nikh13 commented on src/main/java/securbank/services/UserServiceImpl.java
> +		if (!request.getEmail().equals(current.getEmail())) {
Error thrown at this line. I think it should be user.getEmail() and not request.getEmail().

2016-10-18 23:10 UTC, Nikh13 requested changes

2016-10-18 23:10 UTC, Nikh13 commented on src/main/resources/templates/manager/edit.html
> +				<option th:value="ROLE_EMPLOYEE" th:selected="(*{role} == ROLE_EMPLOYEE")>Employee</option>
The double quotes are ending before ')' in the th:selected

2016-10-18 23:11 UTC, Nikh13 commented on src/main/java/securbank/controller/ManagerController.java
> +		if (status == null || !(request.getStatus().equals("approved") || !request.getStatus().equals("rejected"))) {
You've fixed the bug in all the other files but I think you missed it over here.

2016-10-19 00:22 UTC, ayush2k commented on src/main/java/securbank/services/UserServiceImpl.java
> +		if (!request.getEmail().equals(current.getEmail())) {
@Nikh13 `request.getEmail()` is working for me. Email of request is set in the preceding lines. Though the we didn't have the mapping for verifying the email. 
Please confirm if this is correct.
Thanks

2016-10-19 00:22 UTC, ayush2k commented on src/main/resources/templates/manager/edit.html
> +				<option th:value="ROLE_EMPLOYEE" th:selected="(*{role} == ROLE_EMPLOYEE")>Employee</option>
Fixed

2016-10-20 22:12 UTC, Nikh13 approved these changes

2016-10-20 22:12 UTC, merged