Transaction
ayush2k/securbank pull request #86
Opened 2016-10-21 23:47 UTC by Mitikaa

Resolves #44 
Resolves #46 
Description: Transactions

2016-10-22 19:33 UTC, ayush2k requested changes

2016-10-22 19:33 UTC, ayush2k commented on src/main/java/securbank/services/TransactionServiceImpl.java
> +		for(Transfer transf: transferDao.findTransferByFromAccount(account)){
It doesn't has the pending contraint

2016-10-23 02:58 UTC, Mitikaa commented on src/main/java/securbank/controller/ExternalUserController.java
> +		/*if(bindingResult.hasErrors()){
@ayush2k Have disabled validations. Validator form gives errors for Double regex

2016-10-23 02:59 UTC, Mitikaa commented on src/main/java/securbank/controller/ExternalUserController.java
> +		if(transferService.initiateTransfer(transfer)==null){
@ayush2k Model transfer does not map to the Account Number value from template

2016-10-23 03:00 UTC, Mitikaa commented on src/main/resources/templates/external/createtransfer.html
> +        	To: <input type="text" th:field="*{toAccount}" /> </p>
@ayush2k check with controller - mapping for account number

2016-10-23 18:02 UTC, ayush2k commented on src/main/resources/templates/external/createtransfer.html
> +        	To: <input type="text" th:field="*{toAccount}" /> </p>
@Mitikaa its not mapping because toAccount is an object and you are trying to map a number.
The correct mapping would be toAccount.accountNumber.
And this might also throw an error. In that case add an empty object of account during get request

2016-10-23 18:06 UTC, ayush2k commented on src/main/java/securbank/validators/NewTransactionFormValidator.java
> +		if (!errors.hasFieldErrors("amount") && !ContraintUtils.validateTransactionAmount(Double.toString(transaction.getAmount()))) {
@Mitikaa Check if `double.toString` is working fine. Because regex is definitely correct

2016-10-24 08:05 UTC, Nikh13 requested changes
Minor bug fix changes

2016-10-24 08:05 UTC, Nikh13 commented on src/main/java/securbank/controller/EmployeeController.java
> +			if(transactionService.isTransactionValid(transaction)==false){
I think this should be `if(transactionService.isTransactionValid(transaction) ==false && transaction.getType().equals("DEBIT"))`

2016-10-24 08:05 UTC, Nikh13 commented on src/main/java/securbank/controller/EmployeeController.java
> +		if (accountService.accountExists(transfer.getToAccount())) {
`if (`**!**`accountService.accountExists(transfer.getToAccount()))`

2016-10-24 08:05 UTC, Nikh13 commented on src/main/java/securbank/controller/ManagerController.java
> +			if(transactionService.isTransactionValid(transaction)==false){
I think this should be `if(transactionService.isTransactionValid(transaction) ==false && transaction.getType().equals("DEBIT"))`

2016-10-24 08:05 UTC, Nikh13 commented on src/main/java/securbank/controller/ManagerController.java
> +		if (accountService.accountExists(transfer.getToAccount())) {
`if (`**!**`accountService.accountExists(transfer.getToAccount()))`

2016-10-24 08:16 UTC, Mitikaa commented on src/main/java/securbank/controller/EmployeeController.java
> +			if(transactionService.isTransactionValid(transaction)==false){
Nice catch! Thanks! Will update

2016-10-24 08:30 UTC, Mitikaa commented on src/main/java/securbank/controller/ManagerController.java
> +			if(transactionService.isTransactionValid(transaction)==false){
@Nikh13 Have made your suggested changes and pushed them. Let me know if anything else needs to be changed before you merge this.

2016-10-24 08:44 UTC, Nikh13 approved these changes

2016-10-24 08:46 UTC, merged